title:   Avinash Varma
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Result-driven Data Analyst with a strong foundation in Business Intelligence and over 2 years of hands-on experience in data driven projects. Proven expertise in SQL, Power BI, Python and Tableau with the ability to clean, analyze ad visualize complex datasets to support data-driven business decisions. Former financial services and operations professional, experienced in applying data solutions in fast-paced, customer-focused environment. Actively seeking data analyst opportunities in Toronto.
  <br>
  <br>
  <a href="www.linkedin.com/in/avinash-varma-data-analyst">View My LinkedIn</a>
  <br>
  <a href="https://www.notion.so/Portfolio-Avinash-Varma-200bd3ba8d008010a3f3f818f8a62b69">View My Notion Portfolios</a>
theme: jekyll-theme-minimal   
  
 
